### PR TITLE
Remove saved RDS file on failure

### PR DESCRIPTION
**Pull request by krlmlr**
Otherwise we might end up with a broken RDS file that cannot be retrieved later on; remake doesn't handle that situation particularly well. (We might also want to prepare remake for storage failures.)

### CODE REVIEW

**Comment by richfitz** [comment]
Thanks! I can see how that would cause problems.  Any chance you could add a test to go with it?

**Comment by krlmlr** [comment]
How would you simulate the error when writing?

**Comment by richfitz** [comment]
Either via mocking `writeBin` or `try_write_serialized_rds` or by passing something that will definitely cause `writeBin` to fail (e.g., `writeBin(list(), tempfile())`)

**Comment by krlmlr** [comment]
Oh, you're already using with_mock() -- missed that. Will figure out something.

**Comment by richfitz** [comment]
This relates to #42

**Comment by richfitz** [comment]
This has been merged into `develop` via `714f1ef` (though github has not detected that somehow)

**Pull request closed without merging**
